// Permissions Configuration
// Defines all available permission keys and default role assignments

const PERMISSIONS = {
    // 1. Authentication & Profile
    PROFILE_UPDATE_SELF: 'PROFILE_UPDATE_SELF',
    AUTH_PASSWORD_CHANGE: 'AUTH_PASSWORD_CHANGE',
    AUTH_IMPERSONATE: 'AUTH_IMPERSONATE',
    RBAC_ROLE_ASSIGN: 'RBAC_ROLE_ASSIGN',
    ACCOUNT_DELETE: 'ACCOUNT_DELETE',

    // 2. Property Management
    PROPERTY_VIEW_ASSIGNED: 'PROPERTY_VIEW_ASSIGNED',
    PROPERTY_EDIT_DETAILS: 'PROPERTY_EDIT_DETAILS',
    PROPERTY_MANAGE_LISTINGS: 'PROPERTY_MANAGE_LISTINGS',
    UNIT_UPDATE_STATUS: 'UNIT_UPDATE_STATUS',
    PROPERTY_CREATE: 'PROPERTY_CREATE',
    PROPERTY_DELETE: 'PROPERTY_DELETE',
    PROPERTY_VIEW_FINANCIALS: 'PROPERTY_VIEW_FINANCIALS',
    PROPERTY_TRANSFER_OWNERSHIP: 'PROPERTY_TRANSFER_OWNERSHIP',

    // 3. Tenant Management
    TENANT_SCREEN_VIEW: 'TENANT_SCREEN_VIEW',
    TENANT_APPLICATION_MANAGE: 'TENANT_APPLICATION_MANAGE',
    TENANT_CREATE: 'TENANT_CREATE',
    TENANT_VIEW_LIST: 'TENANT_VIEW_LIST',
    TENANT_EXPORT_PII: 'TENANT_EXPORT_PII',
    TENANT_EVICT_EXECUTE: 'TENANT_EVICT_EXECUTE',

    // 4. Lease & Rent Oversight
    LEASE_CREATE_DRAFT: 'LEASE_CREATE_DRAFT',
    LEASE_RENEW_OFFER: 'LEASE_RENEW_OFFER',
    PAYMENT_RECORD_MANUAL: 'PAYMENT_RECORD_MANUAL',
    PAYMENT_VIEW_STATUS: 'PAYMENT_VIEW_STATUS',
    FEE_APPLY: 'FEE_APPLY',
    NOTICE_SERVE: 'NOTICE_SERVE',
    BANK_ACCOUNT_MANAGE: 'BANK_ACCOUNT_MANAGE',
    DEPOSIT_MANAGE: 'DEPOSIT_MANAGE',

    // 5. Maintenance & Vendor Coordination
    MAINTENANCE_TICKET_MANAGE: 'MAINTENANCE_TICKET_MANAGE',
    WORK_ORDER_CREATE: 'WORK_ORDER_CREATE',
    VENDOR_VIEW_LIST: 'VENDOR_VIEW_LIST',
    INSPECTION_MANAGE: 'INSPECTION_MANAGE',
    MAINTENANCE_APPROVE_LOW_VALUE: 'MAINTENANCE_APPROVE_LOW_VALUE',
    VENDOR_ONBOARD: 'VENDOR_ONBOARD',
    MAINTENANCE_APPROVE_HIGH_VALUE: 'MAINTENANCE_APPROVE_HIGH_VALUE',

    // 6. Communication & Notifications
    MESSAGE_SEND_TENANT: 'MESSAGE_SEND_TENANT',
    NOTIFICATION_RECEIVE_OPS: 'NOTIFICATION_RECEIVE_OPS',
    TEMPLATE_MANAGE: 'TEMPLATE_MANAGE',
    MESSAGE_BROADCAST_SYSTEM: 'MESSAGE_BROADCAST_SYSTEM',
    MESSAGE_INTERCEPT_OWNER: 'MESSAGE_INTERCEPT_OWNER',

    // 7. Documents & Media
    DOCUMENT_UPLOAD: 'DOCUMENT_UPLOAD',
    DOCUMENT_VIEW_SHARED: 'DOCUMENT_VIEW_SHARED',
    DOCUMENT_ORGANIZE: 'DOCUMENT_ORGANIZE',
    DOCUMENT_DELETE_LEGAL: 'DOCUMENT_DELETE_LEGAL',
    DOCUMENT_VIEW_FINANCIAL: 'DOCUMENT_VIEW_FINANCIAL',

    // 8. Reports & Dashboards
    REPORT_VIEW_OPERATIONAL: 'REPORT_VIEW_OPERATIONAL',
    REPORT_VIEW_RENT_ROLL: 'REPORT_VIEW_RENT_ROLL',
    LOG_VIEW_SELF: 'LOG_VIEW_SELF',
    REPORT_VIEW_FINANCIAL_PERFORMANCE: 'REPORT_VIEW_FINANCIAL_PERFORMANCE',
    REPORT_VIEW_PLATFORM: 'REPORT_VIEW_PLATFORM',

    // 9. Security & Compliance
    ACCESS_KEY_MANAGE: 'ACCESS_KEY_MANAGE',
    VISITOR_LOG_MANAGE: 'VISITOR_LOG_MANAGE',
    SYSTEM_CONFIG_MANAGE: 'SYSTEM_CONFIG_MANAGE',
    LOG_VIEW_SYSTEM: 'LOG_VIEW_SYSTEM'
};

const ROLES = {
    SUPER_ADMIN: 'super_admin',
    PROPERTY_MANAGER: 'property_manager',
    PROPERTY_OWNER: 'property_owner',
    VENDOR: 'vendor',
    TENANT: 'tenant'
};

const ROLE_PERMISSIONS = {
    [ROLES.PROPERTY_MANAGER]: [
        PERMISSIONS.PROFILE_UPDATE_SELF,
        PERMISSIONS.AUTH_PASSWORD_CHANGE,
        PERMISSIONS.PROPERTY_VIEW_ASSIGNED,
        PERMISSIONS.PROPERTY_EDIT_DETAILS,
        PERMISSIONS.PROPERTY_MANAGE_LISTINGS,
        PERMISSIONS.UNIT_UPDATE_STATUS,
        PERMISSIONS.TENANT_SCREEN_VIEW,
        PERMISSIONS.TENANT_APPLICATION_MANAGE,
        PERMISSIONS.TENANT_CREATE,
        PERMISSIONS.TENANT_VIEW_LIST,
        PERMISSIONS.LEASE_CREATE_DRAFT,
        PERMISSIONS.LEASE_RENEW_OFFER,
        PERMISSIONS.PAYMENT_RECORD_MANUAL,
        PERMISSIONS.PAYMENT_VIEW_STATUS,
        PERMISSIONS.FEE_APPLY,
        PERMISSIONS.NOTICE_SERVE,
        PERMISSIONS.MAINTENANCE_TICKET_MANAGE,
        PERMISSIONS.WORK_ORDER_CREATE,
        PERMISSIONS.VENDOR_VIEW_LIST,
        PERMISSIONS.INSPECTION_MANAGE,
        PERMISSIONS.MAINTENANCE_APPROVE_LOW_VALUE,
        PERMISSIONS.MESSAGE_SEND_TENANT,
        PERMISSIONS.NOTIFICATION_RECEIVE_OPS,
        PERMISSIONS.TEMPLATE_MANAGE,
        PERMISSIONS.DOCUMENT_UPLOAD,
        PERMISSIONS.DOCUMENT_VIEW_SHARED,
        PERMISSIONS.DOCUMENT_ORGANIZE,
        PERMISSIONS.REPORT_VIEW_OPERATIONAL,
        PERMISSIONS.REPORT_VIEW_RENT_ROLL,
        PERMISSIONS.LOG_VIEW_SELF,
        PERMISSIONS.ACCESS_KEY_MANAGE,
        PERMISSIONS.VISITOR_LOG_MANAGE
    ]
};

module.exports = {
    PERMISSIONS,
    ROLES,
    ROLE_PERMISSIONS
};
